export { default as Test } from './Test';
export * from './ui';
export { default as LiberalSystemSwitch } from './LiberalSystemSwitch';
export { default as ScoreRegister } from './register/Step4Register';
export { default as FormController } from './FormController';
export { default as StepWrapper } from './StepWrapper';
export { default as StepBar } from './StepBar';
export * from './form';
export { default as SearchDialog } from './SearchDialog';
export { default as SearchElements } from './SearchElements';
export { default as UploadPhoto } from './UploadPhoto';
export { default as RadioButton } from './RadioButton';
export { default as CustomFormItem } from './CustomFormItem';
export { default as ConfirmBar } from './ConfirmBar';
export { default as EditBar } from './EditBar';
export { default as ScoreCalculateDialog } from './ScoreCalculateDialog';
export { default as InspectionDialog } from './InspectionDialog';
export { default as Step1Register } from './register/Step1Register';
export { default as Step2Register } from './register/Step2Register';
export { default as Step3Register } from './register/Step3Register';
export { default as Step4Register } from './register/Step4Register';
