export { default as SignUpPage } from './SignUpPage';
export { default as MainPage } from './MainPage';
export * from './RegisterPage';
export { default as GuidePage } from './GuidePage';
export { default as MyPage } from './MyPage';
export { default as PrintPage } from './PrintPage';
export { default as FaqPage } from './FaqPage';
export { default as CalculatePage } from './CalculatePage';
export { default as NotFoundPage } from './NotFoundPage';
export { default as ComputerRecommendedPage } from './ComputerRecommendedPage';
export { default as IntroducePage } from './IntroducePage';
export { default as CheckResultPage } from './CheckResultPage';
export { default as CallbackPage } from './CallbackPage';
